
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BudgetTracking.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class BudgetValue
{

    public int ID { get; set; }

    public int BudgetTypeID { get; set; }

    public int Amount { get; set; }

    public System.DateTime Date { get; set; }

    public Nullable<int> RecurringTypeID { get; set; }

    public string Description { get; set; }



    public virtual BudgetType BudgetType { get; set; }

    public virtual RecurringType RecurringType { get; set; }

}

}
